'use client';
import { useMemo, useState } from 'react';
import { PTKP, calculateAnnualPph21ByMethod, calculateMonthlyPph21ByMethod, calculateUmkmFinal, calculateVat, formatRupiah } from '../lib/tax';
import { PPH21_CODE_GROUPS, PPH21_CODES } from '../lib/pph21Codes';

const tabs=[['pph21','PPh 21'],['ppn','PPN'],['umkm','PPh Final UMKM'],['unifikasi','PPh Unifikasi']];
const cards={
 pph21:['Peraturan terbaru · PPh 21','PP 58/2023, PMK 168/2023 & PER-11/PJ/2025','TER berlaku untuk pegawai tetap pada masa selain masa pajak terakhir. Kode objek bukti potong mengikuti PER-11/PJ/2025.'],
 ppn:['Peraturan terbaru · PPN','PMK 131/2024','Transaksi umum non-mewah memakai tarif formal 12% dengan DPP Nilai Lain 11/12 sehingga beban efektif tetap 11%.'],
 umkm:['Peraturan terbaru · PPh Final UMKM','PP 20/2026','Skema PPh Final UMKM 0,5% diperbarui, termasuk subjek, batas waktu, agregasi omzet, dan transisi.'],
 unifikasi:['Peraturan terbaru · PPh Unifikasi','Coretax & PMK 81/2024','Administrasi melalui Coretax; tarif mengikuti objek PPh 4(2), 15, 22, 23, atau 26.']
};
const uni=[['p23j','PPh 23 — Jasa teknik/manajemen/konsultan/jasa lain','PPh Pasal 23',2],['p23s','PPh 23 — Sewa harta selain tanah & bangunan','PPh Pasal 23',2],['p23b','PPh 23 — Bunga, royalti, hadiah tertentu','PPh Pasal 23',15],['sTB','PPh Final 4(2) — Sewa tanah/bangunan','PPh Pasal 4 ayat (2)',10],['k1','PPh Final 4(2) — Konstruksi kecil tersertifikasi','PPh Pasal 4 ayat (2)',1.75],['k2','PPh Final 4(2) — Konstruksi tersertifikasi selain kecil','PPh Pasal 4 ayat (2)',2.65],['k3','PPh Final 4(2) — Konstruksi tanpa sertifikat','PPh Pasal 4 ayat (2)',4],['p15a','PPh 15 — Charter penerbangan dalam negeri','PPh Pasal 15',1.8],['p15p','PPh 15 — Pelayaran dalam negeri','PPh Pasal 15',1.2],['p22a','PPh 22 — Impor API','PPh Pasal 22',2.5],['p22n','PPh 22 — Impor non-API','PPh Pasal 22',7.5],['p22b','PPh 22 — Pembelian barang bendahara/BUMN/BUMD','PPh Pasal 22',1.5],['p22s','PPh 22 — Sistem Informasi Pengadaan','PPh Pasal 22',.5],['p22e','PPh 22 — Emas perhiasan/batangan','PPh Pasal 22',.25],['p26','PPh 26 — WPLN tarif domestik','PPh Pasal 26',20],['custom','Tarif khusus/treaty/objek lain','PPh Unifikasi — tarif khusus',null]];
function Money({label,value,setValue,hint}){return <label className="field"><span>{label}</span><div className="money-input"><span>Rp</span><input type="number" min="0" value={value} onChange={e=>setValue(e.target.value)}/></div>{hint&&<small>{hint}</small>}</label>}
function Row({label,value,strong=false,note}){return <div className={`result-line ${strong?'strong':''}`}><div><span>{label}</span>{note&&<small>{note}</small>}</div><b>{value}</b></div>}
function P21(){
 const[mode,setMode]=useState('monthly'),[method,setMethod]=useState('gross'),[gm,setGm]=useState('10000000'),[status,setStatus]=useState('K/0'),[code,setCode]=useState('21-100-01'),[ag,setAg]=useState('120000000'),[pen,setPen]=useState('1200000'),[months,setMonths]=useState('12'),[prior,setPrior]=useState('2200000');
 const m=useMemo(()=>calculateMonthlyPph21ByMethod({amount:gm,ptkpStatus:status,method}),[gm,status,method]);
 const a=useMemo(()=>calculateAnnualPph21ByMethod({annualGross:ag,pensionContribution:pen,ptkpStatus:status,monthsWorked:months,priorWithheld:prior,method}),[ag,pen,status,months,prior,method]);
 const annual=mode!=='monthly',obj=PPH21_CODES.find(x=>x.code===code),compatible=code==='21-100-01';
 return <div className="calculator-grid"><section className="panel form-panel">
  <div className="method-segmented" style={{gridTemplateColumns:'repeat(2,1fr)'}}>{[['gross','Gross'],['grossUp','Gross Up']].map(([v,l])=><button key={v} className={method===v?'active':''} onClick={()=>setMethod(v)}>{l}</button>)}</div>
  <div className="segmented pph21-mode">{[['monthly','Masa selain terakhir'],['annual','Masa pajak terakhir'],['a1','BP A1']].map(([v,l])=><button key={v} className={mode===v?'active':''} onClick={()=>setMode(v)}>{l}</button>)}</div>
  <label className="field"><span>Status PTKP</span><select value={status} onChange={e=>setStatus(e.target.value)}>{Object.entries(PTKP).map(([k,v])=><option key={k} value={k}>{k} - {formatRupiah(v)}</option>)}</select><small>Batas PTKP sesuai status keluarga pada awal tahun pajak.</small></label>
  <label className="field"><span>Kode objek PPh 21</span><select value={code} onChange={e=>setCode(e.target.value)}>{PPH21_CODE_GROUPS.map(g=><optgroup key={g.label} label={g.label}>{g.options.map(([c,l])=><option key={c} value={c}>{c} — {l}</option>)}</optgroup>)}</select><small>Daftar lengkap mengikuti Lampiran PER-11/PJ/2025.</small></label>
  {!compatible&&<div className="warning-box">Kode ini tersedia untuk kebutuhan administrasi, tetapi formula otomatis modul ini saat ini masih difokuskan pada pegawai tetap 21-100-01 (TER/rekonsiliasi tahunan). Jangan gunakan hasil otomatis untuk kode nonpegawai/final tanpa penelaahan formula objek tersebut.</div>}
  {!annual?<Money label={method==='grossUp'?'Penghasilan sebelum tunjangan pajak bulan ini':'Penghasilan bruto bulan ini'} value={gm} setValue={setGm}/>:<>{mode==='a1'&&<div className="info-box"><b>BP A1 / BPA1</b><br/>Rekonsiliasi tahunan untuk membantu pengecekan bukti potong pegawai tetap/pensiunan.</div>}<Money label="Penghasilan setahun / bagian tahun" value={ag} setValue={setAg}/><Money label="Iuran pensiun/JHT" value={pen} setValue={setPen}/><label className="field"><span>Jumlah bulan bekerja</span><input type="number" min="1" max="12" value={months} onChange={e=>setMonths(e.target.value)}/></label><Money label="PPh 21 sudah dipotong" value={prior} setValue={setPrior}/></>}
 </section><section className="panel result-panel"><div className="eyebrow">{mode==='a1'?'Rekonsiliasi BP A1':'Hasil PPh 21'}</div>{!annual?<><div className="hero-result"><span>PPh 21 masa ini</span><strong>{formatRupiah(m.tax)}</strong></div><Row label="Kode objek" value={`${code} — ${obj?.label||''}`}/><Row label="Status PTKP" value={`${status} — ${formatRupiah(PTKP[status])}`}/><Row label="Kategori TER" value={`Kategori ${m.category}`}/><Row label="Tarif efektif" value={`${m.rate}%`}/><Row label="Nilai dasar" value={formatRupiah(m.baseGross)}/>{method==='grossUp'&&<Row label="Tunjangan pajak" value={formatRupiah(m.taxAllowance)}/>}<Row label="Bruto untuk pajak" value={formatRupiah(m.gross)}/><Row label="Take-home sebelum potongan lain" value={formatRupiah(m.takeHome)} strong/></>:<><div className="hero-result"><span>{a.lastPeriodTax>=0?'PPh 21 masa pajak terakhir':'Kelebihan pemotongan'}</span><strong>{formatRupiah(Math.abs(a.lastPeriodTax))}</strong></div><Row label="Kode objek" value={`${code} — ${obj?.label||''}`}/><Row label="Status PTKP" value={`${status} — ${formatRupiah(PTKP[status])}`}/>{mode==='a1'&&<Row label="1. Penghasilan bruto A1" value={formatRupiah(a.gross)} strong/>}<Row label={mode==='a1'?'2. Biaya jabatan':'Biaya jabatan'} value={formatRupiah(a.positionExpense)}/><Row label={mode==='a1'?'3. Iuran pensiun/JHT':'Iuran pensiun/JHT'} value={formatRupiah(a.pension)}/><Row label={mode==='a1'?'4. Penghasilan neto':'Penghasilan neto'} value={formatRupiah(a.net)}/><Row label={mode==='a1'?'5. PTKP':'PTKP'} value={formatRupiah(a.ptkp)}/><Row label={mode==='a1'?'6. PKP':'PKP'} value={formatRupiah(a.pkp)}/><Row label={mode==='a1'?'7. PPh 21 setahun':'PPh 21 setahun'} value={formatRupiah(a.annualTax)} strong/><Row label={mode==='a1'?'8. PPh 21 telah dipotong':'Sudah dipotong'} value={formatRupiah(a.priorWithheld)}/>{mode==='a1'&&<Row label="9. Selisih masa terakhir" value={formatRupiah(a.lastPeriodTax)} strong/>}</>}</section></div>
}
function PPN(){const[kind,setKind]=useState('nonLuxury'),[inc,setInc]=useState(false),[amt,setAmt]=useState('100000000');const r=useMemo(()=>calculateVat({amount:amt,kind,inclusive:inc}),[amt,kind,inc]);const f=kind==='nonLuxury'?`DPP Nilai Lain = 11/12 × ${formatRupiah(r.preVat)} = ${formatRupiah(r.dpp)} · PPN = 12% × ${formatRupiah(r.dpp)} = ${formatRupiah(r.vat)}`:`PPN = 12% × ${formatRupiah(r.dpp)} = ${formatRupiah(r.vat)}`;return <div className="calculator-grid"><section className="panel form-panel"><label className="field"><span>Jenis transaksi</span><select value={kind} onChange={e=>setKind(e.target.value)}><option value="nonLuxury">BKP non-mewah / JKP umum</option><option value="luxury">BKP mewah tertentu</option></select></label><label className="check-row"><input type="checkbox" checked={inc} onChange={e=>setInc(e.target.checked)}/><span>Nilai sudah termasuk PPN</span></label><Money label={inc?'Nilai termasuk PPN':'Harga jual / penggantian sebelum PPN'} value={amt} setValue={setAmt}/></section><section className="panel result-panel"><div className="eyebrow">Hasil PPN</div><div className="hero-result"><span>PPN terutang</span><strong>{formatRupiah(r.vat)}</strong></div><Row label="Tarif formal" value="12%"/><Row label="Tarif efektif" value={`${Math.round(r.effectiveRate*100)}%`}/><Row label="Harga sebelum PPN" value={formatRupiah(r.preVat)}/><Row label="DPP penghitungan" value={formatRupiah(r.dpp)}/><Row label="Total setelah PPN" value={formatRupiah(r.total)} strong/><div className="formula">{f}</div></section></div>}
function UMKM(){const[type,setType]=useState('individual'),[before,setBefore]=useState('450000000'),[month,setMonth]=useState('100000000'),[prev,setPrev]=useState('1000000000');const r=useMemo(()=>calculateUmkmFinal({taxpayerType:type,priorYtd:before,currentMonth:month}),[type,before,month]);const ok=(Number(prev)||0)<=4800000000;return <div className="calculator-grid"><section className="panel form-panel"><label className="field"><span>Jenis Wajib Pajak</span><select value={type} onChange={e=>setType(e.target.value)}><option value="individual">Orang Pribadi</option><option value="soleCompany">Perseroan Perorangan</option><option value="cooperative">Koperasi</option><option value="transition">CV / Firma / PT biasa / BUMDes</option></select></label><Money label="Peredaran bruto tahun sebelumnya" value={prev} setValue={setPrev}/><Money label="Omzet sebelum bulan ini" value={before} setValue={setBefore}/><Money label="Omzet bulan ini" value={month} setValue={setMonth}/></section><section className="panel result-panel"><div className="eyebrow">Hasil PPh Final UMKM</div><div className="hero-result"><span>PPh Final bulan ini</span><strong>{ok?formatRupiah(r.tax):'Periksa kelayakan'}</strong></div><Row label="Omzet sebelum bulan ini" value={formatRupiah(r.before)}/><Row label="Omzet bulan ini" value={formatRupiah(r.month)}/><Row label="Omzet kumulatif" value={formatRupiah(r.after)}/><Row label="Omzet dikenai 0,5%" value={formatRupiah(r.taxableTurnover)}/><Row label="Tarif" value="0,5%" strong/></section></div>}
function UNI(){const[id,setId]=useState('p23j'),[amt,setAmt]=useState('100000000'),[cr,setCr]=useState('1.5');const x=uni.find(a=>a[0]===id)||uni[0],rate=x[3]??Math.max(0,Number(cr)||0),gross=Math.max(0,Number(amt)||0),tax=Math.round(gross*rate/100);return <div className="calculator-grid"><section className="panel form-panel"><label className="field"><span>Jenis objek PPh Unifikasi</span><select value={id} onChange={e=>setId(e.target.value)}>{uni.map(a=><option key={a[0]} value={a[0]}>{a[1]}</option>)}</select></label><Money label="Jumlah bruto / dasar pemotongan" value={amt} setValue={setAmt}/>{id==='custom'&&<label className="field"><span>Tarif yang berlaku (%)</span><input type="number" value={cr} onChange={e=>setCr(e.target.value)}/></label>}</section><section className="panel result-panel"><div className="eyebrow">Hasil PPh Unifikasi</div><div className="hero-result"><span>PPh dipotong / dipungut</span><strong>{formatRupiah(tax)}</strong></div><Row label="Jenis PPh" value={x[2]}/><Row label="Objek" value={x[1]}/><Row label="Tarif" value={`${rate}%`}/><Row label="Dasar pemotongan" value={formatRupiah(gross)}/></section></div>}
export default function TaxCalculator(){const[active,setActive]=useState('pph21'),c=cards[active];return <main><header className="topbar"><div className="brand-mark">KP</div><div className="brand-copy"><b>Kalkulator Pajak Kantor Kencana</b><span>Indonesia</span></div><div className="verified-pill">Aturan diverifikasi 20 Agustus 2026</div></header><section className="hero"><div className="hero-copy"><div className="eyebrow">Kalkulator pajak Kantor Kencana</div><h1>Hitung Pajak dengan lebih <em>praktis</em>.</h1><p>PPh 21, PPN, PPh Final UMKM, dan PPh Unifikasi dalam satu kalkulator.</p></div><div className="law-card"><span>{c[0]}</span><strong>{c[1]}</strong><p>{c[2]}</p></div></section><nav className="tabs">{tabs.map(([id,l])=><button key={id} className={active===id?'active':''} onClick={()=>setActive(id)}>{l}</button>)}</nav>{active==='pph21'&&<P21/>}{active==='ppn'&&<PPN/>}{active==='umkm'&&<UMKM/>}{active==='unifikasi'&&<UNI/>}<footer><p><b>Catatan:</b> Kalkulator ini membantu estimasi dan bukan pengganti bukti potong, Coretax/DJP, atau penelaahan profesional.</p></footer></main>}