export const PPH21_CODE_GROUPS = [
  {
    label: 'BPA1 / BPA2 — Pegawai tetap dan pensiunan',
    options: [
      ['21-100-01', 'Penghasilan Pegawai Tetap', true],
      ['21-100-02', 'Penghasilan Pensiunan secara Teratur', false],
      ['21-100-32', 'Penghasilan Pegawai Tetap dengan Fasilitas di Daerah Tertentu', false],
    ],
  },
  {
    label: 'BP21 — PPh Pasal 21 Tidak Final',
    options: [
      ['21-100-04', 'Imbalan kepada Distributor Pemasaran Berjenjang atau Penjualan Langsung', false],
      ['21-100-05', 'Imbalan kepada Agen Asuransi', false],
      ['21-100-06', 'Imbalan kepada Petugas Penjaja Barang Dagangan', false],
      ['21-100-07', 'Imbalan kepada Tenaga Ahli', false],
      ['21-100-10', 'Honorarium/Imbalan Anggota Dewan Komisaris atau Dewan Pengawas Tidak Teratur', false],
      ['21-100-11', 'Penghasilan/Imbalan Mantan Pegawai yang Bersifat Tidak Teratur', false],
      ['21-100-12', 'Pengambilan Sebagian Manfaat Pensiun oleh Peserta yang Masih Pegawai', false],
      ['21-100-14', 'Imbalan Peserta Rapat, Konferensi, Seminar, Lokakarya, Pertunjukan, atau Kegiatan Tertentu', false],
      ['21-100-15', 'Imbalan Peserta/Anggota Kepanitiaan', false],
      ['21-100-16', 'Imbalan Peserta Pendidikan, Pelatihan, dan Magang', false],
      ['21-100-17', 'Imbalan Peserta Kegiatan Lainnya', false],
      ['21-100-18', 'Imbalan Penasihat, Pengajar, Pelatih, Penceramah, Penyuluh, dan Moderator', false],
      ['21-100-19', 'Imbalan Pengarang, Peneliti, dan Penerjemah', false],
      ['21-100-20', 'Imbalan Pemberi Jasa dalam Segala Bidang', false],
      ['21-100-21', 'Imbalan Agen Iklan', false],
      ['21-100-22', 'Imbalan Pengawas atau Pengelola Proyek', false],
      ['21-100-23', 'Imbalan Pembawa Pesanan/Pencari Langganan/Perantara', false],
      ['21-100-24', 'Upah Pegawai Tidak Tetap Harian/Mingguan/Satuan/Borongan sampai Rp2,5 juta sehari', false],
      ['21-100-25', 'Pesangon/Manfaat Pensiun/THT/JHT Tahun Ketiga dan Berikutnya', false],
      ['21-100-30', 'Upah Pegawai Tidak Tetap Harian/Mingguan/Satuan/Borongan lebih Rp2,5 juta sehari', false],
      ['21-100-33', 'Imbalan Seniman, Kru, Model, Kreator Konten/Influencer, dan Sejenisnya', false],
      ['21-100-34', 'Imbalan Olahragawan', false],
      ['21-100-35', 'Upah Pegawai Tidak Tetap yang Dibayarkan secara Bulanan', false],
      ['21-100-36', 'Imbalan Peserta Perlombaan dalam Segala Bidang', false],
    ],
  },
  {
    label: 'BP21 — PPh Pasal 21 Final',
    options: [
      ['21-100-27', 'Upah Pegawai Tidak Tetap Bulanan dengan Fasilitas di Daerah Tertentu', false],
      ['21-100-29', 'Upah Pegawai Tidak Tetap sampai Rp2,5 juta sehari dengan Fasilitas di Daerah Tertentu', false],
      ['21-100-31', 'Upah Pegawai Tidak Tetap lebih Rp2,5 juta sehari dengan Fasilitas di Daerah Tertentu', false],
      ['21-100-37', 'Penghasilan Pegawai Tetap di Daerah Tertentu yang Tidak Memenuhi Persyaratan Fasilitas', false],
      ['21-401-01', 'Uang Pesangon yang Dibayarkan Sekaligus', false],
      ['21-401-02', 'Uang Manfaat Pensiun/THT/JHT yang Dibayarkan Sekaligus', false],
      ['21-402-02', 'Honor APBN/APBD PNS Gol. III/TNI-POLRI Perwira Pertama dan Pensiunannya', false],
      ['21-402-03', 'Honor APBN/APBD Pejabat Negara/PNS Gol. IV/Perwira Menengah-Tinggi dan Pensiunannya', false],
      ['21-402-04', 'Honor APBN/APBD PNS Gol. I-II/TNI-POLRI Tamtama-Bintara dan Pensiunannya', false],
      ['21-100-38', 'Penyesuaian Nilai Kompensasi dari Masa Pajak Sebelumnya', false],
    ],
  },
];

export const PPH21_CODES = PPH21_CODE_GROUPS.flatMap((g) => g.options.map(([code, label, compatible]) => ({ code, label, compatible })));
